name: get sub file

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
        # Runs everyday at 2:00 AM
        - cron: "30 17 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main
        
      - name: Push changes
        run: |
          git push origin main

###
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Clone Sub File
        run: |
          wget -O PubSub.txt "https://cf-workers-sub-5ip.pages.dev/sub?token=2eba79ce6f5f05e1f20d202824369273&b64" || echo "⚠️ Failed to download PubSub.txt"
          wget -O PubSubClash.txt "https://cf-workers-sub-5ip.pages.dev/sub?token=2eba79ce6f5f05e1f20d202824369273&clash" || echo "⚠️ Failed to download PubSubClash.txt"
          wget -O bv311.txt "https://aged-shape-cd8a.xzb2022.workers.dev/sub/7374c104-af41-4b29-ade5-e591a76a5eeb#BPB-Normal" || echo "⚠️ Failed to download bv311.txt"
          wget -O bv311Clash.txt "https://aged-shape-cd8a.xzb2022.workers.dev/sub/7374c104-af41-4b29-ade5-e591a76a5eeb?app=clash#BPB-Full-Normal" || echo "⚠️ Failed to download bv311Clash.txt"
          wget -O BPBv313.txt "https://bv3-test.pages.dev/sub/0aa47865-9097-4814-8a4b-1961310c296e#BPB-Normal" || echo "⚠️ Failed to download BPBv313.txt"
          wget -O BPBv313Clash.txt "https://bv3-test.pages.dev/sub/0aa47865-9097-4814-8a4b-1961310c296e?app=clash#BPB-Full-Normal" || echo "⚠️ Failed to download BPBv313Clash.txt"
          wget -O Edge.txt "https://rapid-brook.xzb2022.workers.dev/e737f226-deb4-484f-a795-ad2802e903b3/ty" || echo "⚠️ Failed to download Edge.txt"
          wget -O EdgeClash.txt "https://rapid-brook.xzb2022.workers.dev/e737f226-deb4-484f-a795-ad2802e903b3/cl" || echo "⚠️ Failed to download EdgeClash.txt"
          wget -O EdgeFast.txt "https://rapid-brook-fast.xzb2022.workers.dev/f7edb999-18c7-49ec-9e2d-440c3828fe05/ty" || echo "⚠️ Failed to download EdgeFast.txt"
          wget -O EdgeFastClash.txt "https://rapid-brook-fast.xzb2022.workers.dev/f7edb999-18c7-49ec-9e2d-440c3828fe05/cl" || echo "⚠️ Failed to download EdgeFastClash.txt"
          echo "clone done" 

      - name: Output List File
        run: |
          echo "脚本运行时间：$(TZ=Asia/Shanghai date +'%F %T %Z%:z')" > sub_list.txt
          for file in *.txt; do
            # 排除 sub_list.txt 文件
            if [ "$file" != "sub_list.txt" ]; then
              # 输出文件路径
              echo "$file"
              # 将文件路径替换成 https://gh-proxy.com/raw.githubusercontent.com/happymy/VSUB_TEST/refs/heads/main/ 后缀为文件名
              echo "https://gh-proxy.com/raw.githubusercontent.com/happymy/VSUB_TEST/refs/heads/main/${file%.txt}.txt"  >> sub_list.txt
            fi
          done

          echo "以后仅支持V2rayN和Clash客户端!!!!!" >> sub_list.txt
          echo "V2rayN用不带clash的txt，Clash用带Clash文件名的txt!!!!!" >> sub_list.txt
          echo "超级备胎:https://nodefree.me/" >> sub_list.txt
          
          echo "OUTPUT done"

# echo "当前时间：$(date +'%F %T')" >> PubSub.txt
# echo "当前时间：$(date +'%F %T')" >> PubSubClash.txt
# echo "当前时间：$(date +'%F %T')" >> BPBv3.txt
# echo "当前时间：$(date +'%F %T')" >> BPBv3Clash.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新订阅文件'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: --force
