name: get sub file

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
        # Runs everyday at 2:00 AM
        - cron: "30 17 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin main
        
      - name: Push changes
        run: |
          git push origin main

###
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Clone Sub File
        run: |
          wget -O PubSub.txt "https://cf-workers-sub-5ip.pages.dev/sub?token=2eba79ce6f5f05e1f20d202824369273&b64"
          wget -O PubSubClash.txt "https://cf-workers-sub-5ip.pages.dev/sub?token=2eba79ce6f5f05e1f20d202824369273&clash"
          wget -O BPBv3.txt https://bv3-test.pages.dev/sub/0aa47865-9097-4814-8a4b-1961310c296e#BPB-Normal
          wget -O BPBv3Clash.txt https://bv3-test.pages.dev/sub/0aa47865-9097-4814-8a4b-1961310c296e?app=clash#BPB-Full-Normal 
          wget -O Edge.txt https://rapid-brook.xzb2022.workers.dev/e737f226-deb4-484f-a795-ad2802e903b3/ty
          wget -O EdgeClash.txt https://rapid-brook.xzb2022.workers.dev/e737f226-deb4-484f-a795-ad2802e903b3/cl
          wget -O EdgeFast.txt https://rapid-brook-fast.xzb2022.workers.dev/f7edb999-18c7-49ec-9e2d-440c3828fe05/ty
          wget -O EdgeFastClash.txt https://rapid-brook-fast.xzb2022.workers.dev/f7edb999-18c7-49ec-9e2d-440c3828fe05/cl

# echo "当前时间：$(date +'%F %T')" >> PubSub.txt
# echo "当前时间：$(date +'%F %T')" >> PubSubClash.txt
# echo "当前时间：$(date +'%F %T')" >> BPBv3.txt
# echo "当前时间：$(date +'%F %T')" >> BPBv3Clash.txt

          



    
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新订阅文件'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: --force
          #'--set-upstream'


      
